name: horizon
recipe: laravel
config:
  php: "8.1"
  webroot: public
  via: nginx
  cache: redis
  database: mysql:8.0
  xdebug: true
  # config:
  #   vhosts: .lando/nginx.conf
services:
  appserver:
    type: php:8.1
    composer_version: 2-latest
    xdebug: true
  node:
    type: node:16
tooling:
  npm:
    service: node
  npx:
    service: node
  npm_prod:
    description: Build messages.json and run npm production
    cmd:
      - node: npm run prod