name: laravel_horizon
services:
  node:
    type: node:18
    ssl: true
    ports:
    - 3020:3020
  # web:
  #   type: nginx
  #   ssl: true  
proxy:
  node: 
    - laravel_horizon.lndo.site:3020
tooling:
  npm:
    service: node
  npx:
    service: node
  fdk:
    service: node
  npm_prod:
    service: node
    cmd: npm run build
